version: "3.8"

services:
  calculo-juros-api:
    build:
      context: calculo-juros/
    image: calculo-juros-api
    container_name: calculo-juros-api
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}

  taxa-juros-api:
    build:
      context: taxa-juros/
    image: taxa-juros-api
    container_name: taxa-juros-api
    ports:
      - 5001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
